CREATE VIEW CUSTOMER_BILL
AS 
SELECT C.CustID,C.Name,CASE WHEN AVG(SQ.Consumption_Units) IS NULL THEN 0 ELSE AVG(SQ.Consumption_Units) END AS AverageConsumption, 
CASE WHEN AVG(SQ.Bill_Amount) IS NULL THEN 0 ELSE AVG(SQ.Bill_Amount) END AS AverageBillAmount
FROM CUSTOMER C LEFT JOIN ACCOUNT A 
ON C.CustID=A.CustID
LEFT JOIN (SELECT MR.AccountID,Consumption_Units,Bill_Amount FROM METER_READING MR
JOIN BILL B
ON B.MeterID=MR.MeterID
)SQ
ON SQ.AccountID = A.AccountID
GROUP BY C.CustID, C.Name


GO

CREATE VIEW TOP_EMPLOYEES
AS
SELECT TOP(5) * FROM (SELECT C.CrewID,C.Name, SUM(CASE WHEN  CA.OutageID IS NOT NULL THEN 1 ELSE 0 END) +
SUM(CASE WHEN EI.EquipmentID IS NOT NULL THEN 1 ELSE 0 END) AS TotalAssignments
FROM CREW C LEFT JOIN CREW_ASSIGNMENTS CA
ON CA.CrewID=C.CrewID
LEFT JOIN EQUIPMENT_INSTALLATION EI
ON EI.Installed_by_crew=C.CrewID
GROUP BY C.CrewID,C.Name)SQ
ORDER BY SQ.TotalAssignments DESC

GO

CREATE VIEW OUTAGES_PER_MONTH
AS
SELECT COUNT(*) AS NumOutages, MonthYear FROM
(SELECT DATEFROMPARTS(YEAR(Start_Time),MONTH(Start_Time), 1) AS [MonthYear], *
FROM OUTAGES) SQ
GROUP BY MonthYear

GO



select * from outages;